language: rust
rust:
  - 1.36.0
  - stable
  - beta
  - nightly
dist: xenial
branches:
  only:
    - staging
    - trying
    - master
  except:
    - staging.tmp
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - sudo apt-get -qq update && sudo apt-get -qq install libsdl2-dev # SDL
  - rustup target add wasm32-unknown-unknown
  - cargo install -f cargo-web
  - cargo build --verbose --features sdl2,glutin
  - cargo build --verbose --target wasm32-unknown-unknown
  - cargo web build --verbose --no-default-features --features stdweb
  - cargo test --verbose
  - (cd examples/hello &&
    cargo build --features window-glutin &&
    cargo build --features window-sdl2 &&
    cargo build --target wasm32-unknown-unknown &&
    cargo web build --no-default-features --features stdweb)
